- hosts: localhost
  become: true
  vars_files:
    - settings.yml
  pre_tasks:
      - name: Install playbook requirements
        become: true
        package:
         name:
          - python3-psutil
          - dconf
          - dbus-tools
          - dbus-daemon
  tasks:

   - include: tasks/tweaks.yml
   - include: tasks/gnome.yml
   - include: tasks/packages.yml


